//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognitivo.Sales {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class PackingListSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static PackingListSetting defaultInstance = ((PackingListSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PackingListSetting())));
        
        public static PackingListSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TransDate_OffSet {
            get {
                return ((int)(this["TransDate_OffSet"]));
            }
            set {
                this["TransDate_OffSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool quicklook_AvailableCredit {
            get {
                return ((bool)(this["quicklook_AvailableCredit"]));
            }
            set {
                this["quicklook_AvailableCredit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool quicklook_Telephone {
            get {
                return ((bool)(this["quicklook_Telephone"]));
            }
            set {
                this["quicklook_Telephone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool quicklook_Branch {
            get {
                return ((bool)(this["quicklook_Branch"]));
            }
            set {
                this["quicklook_Branch"] = value;
            }
        }
    }
}
