//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognitivo.Menu {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class appListSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static appListSetting defaultInstance = ((appListSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new appListSetting())));
        
        public static appListSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Fav</string>
  <string>Sales</string>
  <string>Purchase</string>
  <string>Stock</string>
  <string>Project</string>
  <string>Production</string>
  <string>Finance</string>
  <string>Accounting</string>
  <string>HR</string>
  <string>Config</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection modList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["modList"]));
            }
            set {
                this["modList"] = value;
            }
        }
    }
}
