//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity.Brillo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class WeatherSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static WeatherSettings defaultInstance = ((WeatherSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WeatherSettings())));
        
        public static WeatherSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Temp_Celcius {
            get {
                return ((bool)(this["Temp_Celcius"]));
            }
            set {
                this["Temp_Celcius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.openweathermap.org/data/2.5/weather?lat=35&lon=139")]
        public string WeatherAPI {
            get {
                return ((string)(this["WeatherAPI"]));
            }
            set {
                this["WeatherAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int Update_Interval {
            get {
                return ((int)(this["Update_Interval"]));
            }
            set {
                this["Update_Interval"] = value;
            }
        }
    }
}
