//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognitivo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool open_Window {
            get {
                return ((bool)(this["open_Window"]));
            }
            set {
                this["open_Window"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string language_ISO {
            get {
                return ((string)(this["language_ISO"]));
            }
            set {
                this["language_ISO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool developer_Option {
            get {
                return ((bool)(this["developer_Option"]));
            }
            set {
                this["developer_Option"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainMenu_Corporate {
            get {
                return ((bool)(this["mainMenu_Corporate"]));
            }
            set {
                this["mainMenu_Corporate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wallpaper_Image {
            get {
                return ((string)(this["wallpaper_Image"]));
            }
            set {
                this["wallpaper_Image"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Continue_OnException {
            get {
                return ((bool)(this["Continue_OnException"]));
            }
            set {
                this["Continue_OnException"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://debehaber.com")]
        public string DebeHaberConnString {
            get {
                return ((string)(this["DebeHaberConnString"]));
            }
            set {
                this["DebeHaberConnString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Fav</string>
  <string>Purchase</string>
  <string>Sales</string>
  <string>Stock</string>
  <string>Impex</string>
  <string>Finance</string>
  <string>HumanResources</string>
  <string>Accounting</string>
  <string>Project_Event</string>
  <string>Project_PrintingPress</string>
  <string>Project</string>
  <string>Production</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ModFavList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ModFavList"]));
            }
            set {
                this["ModFavList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection AppFavList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AppFavList"]));
            }
            set {
                this["AppFavList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N2")]
        public string QuantityDecimalStringFormat {
            get {
                return ((string)(this["QuantityDecimalStringFormat"]));
            }
            set {
                this["QuantityDecimalStringFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultCustomer {
            get {
                return ((int)(this["DefaultCustomer"]));
            }
            set {
                this["DefaultCustomer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N2")]
        public string CurrencyDecimalStringFormat {
            get {
                return ((string)(this["CurrencyDecimalStringFormat"]));
            }
            set {
                this["CurrencyDecimalStringFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImYzNDE0NGYxOTdjZWJlODEwMWM2NTFlYzZiNzhiNTA4OWY4NWM2MDFmYzk5ZjQ3M2E1MTc0MDNiOTQ0YTkzYTE2NzQ0NDkwZjE5OTEwYzFhIn0.eyJhdWQiOiIxIiwianRpIjoiZjM0MTQ0ZjE5N2NlYmU4MTAxYzY1MWVjNmI3OGI1MDg5Zjg1YzYwMWZjOTlmNDczYTUxNzQwM2I5NDRhOTNhMTY3NDQ0OTBmMTk5MTBjMWEiLCJpYXQiOjE1NTA2NDMyMzksIm5iZiI6MTU1MDY0MzIzOSwiZXhwIjoxNTgyMTc5MjM5LCJzdWIiOiI1MyIsInNjb3BlcyI6W119.P3GfOT78zmgezJ48w0cCkuw0JA7fxZxNbAbellPBX4fOP2dJ4TAqqRzHugIazsBJ83sCIVrLIrZhljEXtcAGqFB-AVwxoIk7VRFr93AN6MZBATKUmgjl9cOoGOZZLf7TPJxwO-jxf05eq3O239Eb-CWtkAP4F6Kc2pBW5Rj0p27MSxet_MFHavv2airTJKMAI1FFnwdOUL47bQ0LiwERez6puDUcpAgNlJ-MQiLlTbykpB3hh-otMr9MnXZ9P0ogFujh5zLQaBIBdxyKByFEyZ9BcScy6p2v-Qvb9gOFf-iYqP8DTDZIzrUlGfBXkAA40OEb_twLES4pF9HNTriu6IuNK6Vpwdh8ZHq00eXXaR4aGAK2OFUyIYT889H0bus661kaAFPnO-hLyzYJxKlc6uLHpxLcVseOQQET9hUvOvi_HDWvQRSd1jfyHBZSAZnEB7Pvg7R4H-HfsbTVBKwt5jy-eTE58dwXeC3F-zSWM5qkyYZ8i5Evt_kaNz6lALUCiSezSgzVcByw48c1UYz46XAV-UnZvBt_SlHQb5ebhKjbovm2bNiPnrqno2QNynxMsjGMplah3CkzVsWffhLPH3lPlRwBsCxuD3rEOs4BNvRU1oDjW6xGK02X3u-mk-q7tUXKzjaW9NS8sj0Ys1D-rG2gffWkwwM5B8LFqr53Jao")]
        public string CognitivoKey {
            get {
                return ((string)(this["CognitivoKey"]));
            }
            set {
                this["CognitivoKey"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;user id=root;password=root;persistsecurityinfo=True;database=bym" +
            "")]
        public string MySQLconnString {
            get {
                return ((string)(this["MySQLconnString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bym")]
        public string Slug {
            get {
                return ((string)(this["Slug"]));
            }
            set {
                this["Slug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SyncType {
            get {
                return ((int)(this["SyncType"]));
            }
            set {
                this["SyncType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PaymentLoadData {
            get {
                return ((bool)(this["PaymentLoadData"]));
            }
            set {
                this["PaymentLoadData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayMainContact {
            get {
                return ((bool)(this["DisplayMainContact"]));
            }
            set {
                this["DisplayMainContact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
    }
}
