// <auto-generated />
namespace entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updatecontact_subsciption : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatecontact_subsciption));
        
        string IMigrationMetadata.Id
        {
            get { return "201603071003546_Updatecontact_subsciption"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
