namespace entity.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Currencychange : DbMigration
    {
        public override void Up()
        {
            AlterColumn("accounting_budget", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("accounting_journal_detail", "debit", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("accounting_journal_detail", "credit", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("app_branch", "area", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_branch", "geo_lat", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_branch", "geo_long", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_geography", "geo_long", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_geography", "geo_lat", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_account", "initial_amount", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_account_detail", "debit", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("app_account_detail", "credit", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("security_user", "id_company", c => c.Int());
            AlterColumn("app_currency", "id_company", c => c.Int());
            AlterColumn("app_currency_denomination", "id_company", c => c.Int());
            AlterColumn("app_currencyfx", "buy_value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("app_currencyfx", "sell_value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("app_currencyfx", "id_company", c => c.Int());
            AlterColumn("impex_expense", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("impex_expense", "currency_rate", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("contacts", "credit_limit", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("contacts", "geo_lat", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("contacts", "geo_long", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("contacts", "id_company", c => c.Int());
            AlterColumn("app_contract_detail", "coefficient", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("contact_subscription", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("items", "unit_cost", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("items", "id_company", c => c.Int());
            AlterColumn("app_measurement", "id_company", c => c.Int());
            AlterColumn("app_measurement_type", "id_company", c => c.Int());
            AlterColumn("item_conversion_factor", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_product", "stock_min", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_product", "stock_max", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_movement", "id_sales_invoice_detail", c => c.Int());
            AlterColumn("item_movement", "debit", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_movement", "credit", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_movement_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("app_dimension", "id_company", c => c.Int());
            AlterColumn("item_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("project_task_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("project_task", "quantity_est", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("project_task", "unit_cost_est", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("payment_detail", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("payment_schedual", "debit", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("payment_schedual", "credit", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("payment_promissory_note", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("payment_promissory_note", "interest", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("app_weather", "temp", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_weather", "temp_min", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_weather", "temp_max", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_weather", "pressure", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_weather", "humidity", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_weather", "wind_speed", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_weather", "wind_type", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("app_weather", "wind_direction", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("payment_withholding_tax", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("crm_opportunity", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("production_execution_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("production_execution_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("hr_time_coefficient", "coefficient", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_asset_maintainance_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_asset_maintainance_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_asset", "purchase_value", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_asset", "current_value", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_asset", "speed", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_asset", "dieset_price", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_asset", "min_length", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_asset", "max_length", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_asset", "min_width", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_asset", "max_width", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_asset_group", "depreciation_rate", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_request_detail", "max_value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_request_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_request_decision", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_request_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("production_order_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("production_order_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_order_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_order_detail", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_order_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_order_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("app_vat", "coefficient", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_budget_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_budget_detail", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_budget_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_budget_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_invoice_detail", "id_sales_invoice_detail", c => c.Int(nullable: false, identity: true));
            AlterColumn("sales_invoice_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_invoice_detail", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_invoice_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_invoice_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_packing_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_rep", "commision_base", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("production_execution_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_return_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_return_detail", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_return_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_return_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_invoice_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_invoice_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_invoice_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_invoice_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_order_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_order_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_order_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_tender_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_tender_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_tender_detail_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_tender_item", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_tender_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_order_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_return_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_return_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_return_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_return_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_movement_value", "unit_value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_transfer_detail", "quantity_origin", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_transfer_detail", "quantity_destination", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_transfer_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_price", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_price", "min_quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_price_list", "percent_over", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_price_list", "id_company", c => c.Int());
            AlterColumn("item_property", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_recepie", "id_item", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_recepie_detail", "id_recepie", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_recepie_detail", "id_item", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_recepie_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("hr_talent_detail", "experience", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("project_event_fixed", "consumption", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("project_event_template_variable", "adult_consumption", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("project_event_template_variable", "child_consumption", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("project_event_variable", "adult_consumption", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("project_event_variable", "child_consumption", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("hr_contract", "base_salary", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("hr_education", "average", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("security_role_privilage", "value_max", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("accounting_template_detail", "coefficeint", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("app_branch_walkins", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_inventory_detail", "value_system", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_inventory_detail", "value_counted", c => c.Decimal(precision: 20, scale: 9));
            AlterColumn("item_inventory_detail", "unit_value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("item_inventory_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_packing_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("purchase_packing_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_promotion", "quantity_min", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_promotion", "quantity_max", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_promotion", "quantity_step", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_promotion", "result_value", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            AlterColumn("sales_promotion", "result_step", c => c.Decimal(nullable: false, precision: 20, scale: 9));
            DropPrimaryKey("item_movement_dimension");
            DropPrimaryKey("sales_invoice_detail");
            DropPrimaryKey("security_crud");
            RenameTable(name: "security_curd", newName: "security_crud");
            DropForeignKey("security_user", "id_company", "app_company");
            DropForeignKey("app_currency", "id_company", "app_company");
            DropForeignKey("app_currency_denomination", "id_company", "app_company");
            DropForeignKey("app_currencyfx", "id_company", "app_company");
            DropForeignKey("contacts", "id_company", "app_company");
            DropForeignKey("items", "id_company", "app_company");
            DropForeignKey("app_measurement", "id_company", "app_company");
            DropForeignKey("app_measurement_type", "id_company", "app_company");
            DropForeignKey("app_dimension", "id_company", "app_company");
            DropForeignKey("sales_packing_relation", "id_sales_invoice_detail", "sales_invoice_detail");
            DropForeignKey("sales_return_detail", "id_sales_invoice_detail", "sales_invoice_detail");
            DropForeignKey("item_price_list", "id_company", "app_company");
            DropForeignKey("item_movement", "id_sales_invoice_detail", "sales_invoice_detail");
            DropIndex("security_user", new[] { "id_company" });
            DropIndex("app_currency", new[] { "id_company" });
            DropIndex("app_currency_denomination", new[] { "id_company" });
            DropIndex("app_currencyfx", new[] { "id_company" });
            DropIndex("contacts", new[] { "id_company" });
            DropIndex("items", new[] { "id_company" });
            DropIndex("app_measurement", new[] { "id_company" });
            DropIndex("app_measurement_type", new[] { "id_company" });
            DropIndex("item_movement", new[] { "id_sales_invoice_detail" });
            DropIndex("app_dimension", new[] { "id_company" });
            DropIndex("sales_packing_relation", new[] { "id_sales_invoice_detail" });
            DropIndex("sales_return_detail", new[] { "id_sales_invoice_detail" });
            DropIndex("item_price_list", new[] { "id_company" });
            RenameColumn(table: "item_movement", name: "_parent_id_movement", newName: "parent_id_movement");
            DropIndex("item_movement", new[] { "IX__parent_id_movement" });
            CreateIndex("item_movement", "IX_parent_id_movement");
          //  RenameIndex(table: "item_movement", name: "IX__parent_id_movement", newName: "IX_parent_id_movement");
            AddColumn("security_role", "see_cost", c => c.Boolean(nullable: false));
            AddColumn("item_movement_dimension", "id_movement_dimension", c => c.Long(nullable: false, identity: true));
            AddColumn("sales_packing_relation", "sales_invoice_detail_id_sales_invoice_detail", c => c.Int());
            AddColumn("sales_return_detail", "sales_invoice_detail_id_sales_invoice_detail", c => c.Int());
            AddColumn("security_crud", "id_crud", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("item_movement_dimension", "id_movement_dimension");
            AddPrimaryKey("sales_invoice_detail", "id_sales_invoice_detail");
            AddPrimaryKey("security_crud", "id_crud");
            CreateIndex("security_user", "id_company");
            CreateIndex("app_currency", "id_company");
            CreateIndex("app_currency_denomination", "id_company");
            CreateIndex("app_currencyfx", "id_company");
            CreateIndex("contacts", "id_company");
            CreateIndex("items", "id_company");
            CreateIndex("app_measurement", "id_company");
            CreateIndex("app_measurement_type", "id_company");
            CreateIndex("item_movement", "id_sales_invoice_detail");
            CreateIndex("app_dimension", "id_company");
            CreateIndex("sales_packing_relation", "sales_invoice_detail_id_sales_invoice_detail");
            CreateIndex("sales_return_detail", "sales_invoice_detail_id_sales_invoice_detail");
            CreateIndex("item_price_list", "id_company");
            AddForeignKey("security_user", "id_company", "app_company", "id_company");
            AddForeignKey("app_currency", "id_company", "app_company", "id_company");
            AddForeignKey("app_currency_denomination", "id_company", "app_company", "id_company");
            AddForeignKey("app_currencyfx", "id_company", "app_company", "id_company");
            AddForeignKey("contacts", "id_company", "app_company", "id_company");
            AddForeignKey("items", "id_company", "app_company", "id_company");
            AddForeignKey("app_measurement", "id_company", "app_company", "id_company");
            AddForeignKey("app_measurement_type", "id_company", "app_company", "id_company");
            AddForeignKey("app_dimension", "id_company", "app_company", "id_company");
            AddForeignKey("sales_packing_relation", "sales_invoice_detail_id_sales_invoice_detail", "sales_invoice_detail", "id_sales_invoice_detail");
            AddForeignKey("sales_return_detail", "sales_invoice_detail_id_sales_invoice_detail", "sales_invoice_detail", "id_sales_invoice_detail");
            AddForeignKey("item_price_list", "id_company", "app_company", "id_company");
            AddForeignKey("item_movement", "id_sales_invoice_detail", "sales_invoice_detail", "id_sales_invoice_detail");
            DropColumn("item_movement_dimension", "id_movement_property");
            DropColumn("security_crud", "id_curd");
        }
        
        public override void Down()
        {
            AddColumn("security_crud", "id_curd", c => c.Int(nullable: false, identity: true));
            AddColumn("item_movement_dimension", "id_movement_property", c => c.Long(nullable: false, identity: true));
            DropForeignKey("item_movement", "id_sales_invoice_detail", "sales_invoice_detail");
            DropForeignKey("item_price_list", "id_company", "app_company");
            DropForeignKey("sales_return_detail", "sales_invoice_detail_id_sales_invoice_detail", "sales_invoice_detail");
            DropForeignKey("sales_packing_relation", "sales_invoice_detail_id_sales_invoice_detail", "sales_invoice_detail");
            DropForeignKey("app_dimension", "id_company", "app_company");
            DropForeignKey("app_measurement_type", "id_company", "app_company");
            DropForeignKey("app_measurement", "id_company", "app_company");
            DropForeignKey("items", "id_company", "app_company");
            DropForeignKey("contacts", "id_company", "app_company");
            DropForeignKey("app_currencyfx", "id_company", "app_company");
            DropForeignKey("app_currency_denomination", "id_company", "app_company");
            DropForeignKey("app_currency", "id_company", "app_company");
            DropForeignKey("security_user", "id_company", "app_company");
            DropIndex("item_price_list", new[] { "id_company" });
            DropIndex("sales_return_detail", new[] { "sales_invoice_detail_id_sales_invoice_detail" });
            DropIndex("sales_packing_relation", new[] { "sales_invoice_detail_id_sales_invoice_detail" });
            DropIndex("app_dimension", new[] { "id_company" });
            DropIndex("item_movement", new[] { "id_sales_invoice_detail" });
            DropIndex("app_measurement_type", new[] { "id_company" });
            DropIndex("app_measurement", new[] { "id_company" });
            DropIndex("items", new[] { "id_company" });
            DropIndex("contacts", new[] { "id_company" });
            DropIndex("app_currencyfx", new[] { "id_company" });
            DropIndex("app_currency_denomination", new[] { "id_company" });
            DropIndex("app_currency", new[] { "id_company" });
            DropIndex("security_user", new[] { "id_company" });
            DropPrimaryKey("security_crud");
            DropPrimaryKey("sales_invoice_detail");
            DropPrimaryKey("item_movement_dimension");
            DropColumn("security_crud", "id_crud");
            DropColumn("sales_return_detail", "sales_invoice_detail_id_sales_invoice_detail");
            DropColumn("sales_packing_relation", "sales_invoice_detail_id_sales_invoice_detail");
            DropColumn("item_movement_dimension", "id_movement_dimension");
            DropColumn("security_role", "see_cost");
            RenameIndex(table: "dbo.item_movement", name: "IX_parent_id_movement", newName: "IX__parent_id_movement");
            RenameColumn(table: "item_movement", name: "parent_id_movement", newName: "_parent_id_movement");
            CreateIndex("item_price_list", "id_company");
            CreateIndex("sales_return_detail", "id_sales_invoice_detail");
            CreateIndex("sales_packing_relation", "id_sales_invoice_detail");
            CreateIndex("app_dimension", "id_company");
            CreateIndex("item_movement", "id_sales_invoice_detail");
            CreateIndex("app_measurement_type", "id_company");
            CreateIndex("app_measurement", "id_company");
            CreateIndex("items", "id_company");
            CreateIndex("contacts", "id_company");
            CreateIndex("app_currencyfx", "id_company");
            CreateIndex("app_currency_denomination", "id_company");
            CreateIndex("app_currency", "id_company");
            CreateIndex("security_user", "id_company");
            AddForeignKey("item_movement", "id_sales_invoice_detail", "sales_invoice_detail", "id_sales_invoice_detail");
            AddForeignKey("item_price_list", "id_company", "app_company", "id_company", cascadeDelete: true);
            AddForeignKey("sales_return_detail", "id_sales_invoice_detail", "sales_invoice_detail", "id_sales_invoice_detail");
            AddForeignKey("sales_packing_relation", "id_sales_invoice_detail", "sales_invoice_detail", "id_sales_invoice_detail", cascadeDelete: true);
            AddForeignKey("app_dimension", "id_company", "app_company", "id_company", cascadeDelete: true);
            AddForeignKey("app_measurement_type", "id_company", "app_company", "id_company", cascadeDelete: true);
            AddForeignKey("app_measurement", "id_company", "app_company", "id_company", cascadeDelete: true);
            AddForeignKey("items", "id_company", "app_company", "id_company", cascadeDelete: true);
            AddForeignKey("contacts", "id_company", "app_company", "id_company", cascadeDelete: true);
            AddForeignKey("app_currencyfx", "id_company", "app_company", "id_company", cascadeDelete: true);
            AddForeignKey("app_currency_denomination", "id_company", "app_company", "id_company", cascadeDelete: true);
            AddForeignKey("app_currency", "id_company", "app_company", "id_company", cascadeDelete: true);
            AddForeignKey("security_user", "id_company", "app_company", "id_company", cascadeDelete: true);
            RenameTable(name: "security_crud", newName: "security_curd");
            AddPrimaryKey("security_crud", "id_curd");
            AddPrimaryKey("sales_invoice_detail", "id_sales_invoice_detail");
            AddPrimaryKey("item_movement_dimension", "id_movement_property");
            AlterColumn("sales_promotion", "result_step", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_promotion", "result_value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_promotion", "quantity_step", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_promotion", "quantity_max", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_promotion", "quantity_min", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_packing_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_packing_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_inventory_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_inventory_detail", "unit_value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_inventory_detail", "value_counted", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_inventory_detail", "value_system", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_branch_walkins", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("accounting_template_detail", "coefficeint", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("security_role_privilage", "value_max", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("hr_education", "average", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("hr_contract", "base_salary", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("project_event_variable", "child_consumption", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("project_event_variable", "adult_consumption", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("project_event_template_variable", "child_consumption", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("project_event_template_variable", "adult_consumption", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("project_event_fixed", "consumption", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("hr_talent_detail", "experience", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_recepie_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_recepie_detail", "id_item", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_recepie_detail", "id_recepie", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_recepie", "id_item", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_property", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_price_list", "id_company", c => c.Int(nullable: false));
            AlterColumn("item_price_list", "percent_over", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_price", "min_quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_price", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_transfer_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_transfer_detail", "quantity_destination", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_transfer_detail", "quantity_origin", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_movement_value", "unit_value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_return_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_return_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_return_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_return_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_order_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_tender_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_tender_item", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_tender_detail_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_tender_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_tender_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_order_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_order_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_order_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_invoice_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_invoice_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_invoice_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("purchase_invoice_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_return_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_return_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_return_detail", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_return_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("production_execution_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_rep", "commision_base", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("sales_packing_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_invoice_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_invoice_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_invoice_detail", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_invoice_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_invoice_detail", "id_sales_invoice_detail", c => c.Long(nullable: false, identity: true));
            AlterColumn("sales_budget_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_budget_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_budget_detail", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_budget_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_vat", "coefficient", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_order_detail", "discount", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_order_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_order_detail", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("sales_order_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("production_order_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("production_order_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_request_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_request_decision", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_request_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_request_detail", "max_value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_asset_group", "depreciation_rate", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_asset", "max_width", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_asset", "min_width", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_asset", "max_length", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_asset", "min_length", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_asset", "dieset_price", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_asset", "speed", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_asset", "current_value", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_asset", "purchase_value", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_asset_maintainance_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_asset_maintainance_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("hr_time_coefficient", "coefficient", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("production_execution_detail", "unit_cost", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("production_execution_detail", "quantity", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("crm_opportunity", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("payment_withholding_tax", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_weather", "wind_direction", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_weather", "wind_type", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_weather", "wind_speed", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_weather", "humidity", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_weather", "pressure", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_weather", "temp_max", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_weather", "temp_min", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_weather", "temp", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("payment_promissory_note", "interest", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("payment_promissory_note", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("payment_schedual", "credit", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("payment_schedual", "debit", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("payment_detail", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("project_task", "unit_cost_est", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("project_task", "quantity_est", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("project_task_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_dimension", "id_company", c => c.Int(nullable: false));
            AlterColumn("item_movement_dimension", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_movement", "credit", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_movement", "debit", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("item_movement", "id_sales_invoice_detail", c => c.Long());
            AlterColumn("item_product", "stock_max", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_product", "stock_min", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("item_conversion_factor", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_measurement_type", "id_company", c => c.Int(nullable: false));
            AlterColumn("app_measurement", "id_company", c => c.Int(nullable: false));
            AlterColumn("items", "id_company", c => c.Int(nullable: false));
            AlterColumn("items", "unit_cost", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("contact_subscription", "unit_price", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_contract_detail", "coefficient", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("contacts", "id_company", c => c.Int(nullable: false));
            AlterColumn("contacts", "geo_long", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("contacts", "geo_lat", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("contacts", "credit_limit", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("impex_expense", "currency_rate", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("impex_expense", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_currencyfx", "id_company", c => c.Int(nullable: false));
            AlterColumn("app_currencyfx", "sell_value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_currencyfx", "buy_value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_currency_denomination", "id_company", c => c.Int(nullable: false));
            AlterColumn("app_currency", "id_company", c => c.Int(nullable: false));
            AlterColumn("security_user", "id_company", c => c.Int(nullable: false));
            AlterColumn("app_account_detail", "credit", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_account_detail", "debit", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("app_account", "initial_amount", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_geography", "geo_lat", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_geography", "geo_long", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_branch", "geo_long", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_branch", "geo_lat", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("app_branch", "area", c => c.Decimal(precision: 20, scale: 4));
            AlterColumn("accounting_journal_detail", "credit", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("accounting_journal_detail", "debit", c => c.Decimal(nullable: false, precision: 20, scale: 4));
            AlterColumn("accounting_budget", "value", c => c.Decimal(nullable: false, precision: 20, scale: 4));
        }
    }
}
