// <auto-generated />
namespace entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_FixedAsset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_FixedAsset));
        
        string IMigrationMetadata.Id
        {
            get { return "201607011305080_Update_FixedAsset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
