//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cntrl.Controls {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class smartBoxItemSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static smartBoxItemSetting defaultInstance = ((smartBoxItemSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new smartBoxItemSetting())));
        
        public static smartBoxItemSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Name</string>
  <string>Code</string>
  <string>SearchExactCode</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SearchFilter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SearchFilter"]));
            }
            set {
                this["SearchFilter"] = value;
            }
        }
    }
}
