//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cntrl.Controls {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class smartBoxContactSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static smartBoxContactSetting defaultInstance = ((smartBoxContactSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new smartBoxContactSetting())));
        
        public static smartBoxContactSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SearchFilter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SearchFilter"]));
            }
            set {
                this["SearchFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool is_principal {
            get {
                return ((bool)(this["is_principal"]));
            }
            set {
                this["is_principal"] = value;
            }
        }
    }
}
