//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognitivo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class GestureSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GestureSettings defaultInstance = ((GestureSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GestureSettings())));
        
        public static GestureSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string SaveKey {
            get {
                return ((string)(this["SaveKey"]));
            }
            set {
                this["SaveKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string SaveModifier {
            get {
                return ((string)(this["SaveModifier"]));
            }
            set {
                this["SaveModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string NewKey {
            get {
                return ((string)(this["NewKey"]));
            }
            set {
                this["NewKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string NewModifier {
            get {
                return ((string)(this["NewModifier"]));
            }
            set {
                this["NewModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string DeleteKey {
            get {
                return ((string)(this["DeleteKey"]));
            }
            set {
                this["DeleteKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string DeleteModifier {
            get {
                return ((string)(this["DeleteModifier"]));
            }
            set {
                this["DeleteModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string CancelKey {
            get {
                return ((string)(this["CancelKey"]));
            }
            set {
                this["CancelKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string CancelModifier {
            get {
                return ((string)(this["CancelModifier"]));
            }
            set {
                this["CancelModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string EditKey {
            get {
                return ((string)(this["EditKey"]));
            }
            set {
                this["EditKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt")]
        public string EditModifier {
            get {
                return ((string)(this["EditModifier"]));
            }
            set {
                this["EditModifier"] = value;
            }
        }
    }
}
